version: 0.2

env:    
  variables:
    bucket: "$bucket"
    region: "$region"
    key: "$key"
    branch: "$branch"

phases:
  build:
    commands:

      - yum install -y yum-utils shadow-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - printf 'yes' | terraform init -backend-config="bucket=$bucket" -backend-config="region=$region" -backend-config="key=$key"
      - terraform workspace list      
      - terraform workspace select $branch || terraform workspace new $branch
      - terraform apply --auto-approve -var "repo_name=$repo_name" -var "repo_branch=$repo_branch" -var "cicd_name=$cicd_name" -var "bucket=$bucket" -var "region=$region" 
